name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Prepare and deploy
        if: github.ref == 'refs/heads/main'
        env:
          GHITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npx ng deploy
