name: Deploy to GitHub Pages via angular-cli-ghpages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install
        npm run ng -- deploy --base-href=/standalone/ --name="TheophileDesmedt" --email=theophiledesmedt@gmail.com
